SET NOCOUNT ON;

DECLARE @Query nvarchar(max) = N'update dbo.B set Counter = 100 where ID > 100'
   --N'DECLARE @C INT; 
   --  SELECT @C = COUNT(*) FROM dbo.D';

/*Run once so compilation out of the way*/
--EXEC(@Query);

DBCC TRACEON(-1,3604,1200) WITH NO_INFOMSGS;

PRINT 'READ UNCOMMITTED';
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
EXEC(@Query);

PRINT 'READ COMMITTED';
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
EXEC(@Query);

DBCC TRACEOFF(-1,3604,1200) WITH NO_INFOMSGS